version: '3'
services:
  api-database:
    image: mongo:4.0.4
    container_name: api-database
    ports:
      - 27017:27017
    command: --smallfiles
    volumes:
      - /data/db
  api:
    image: my-app
    container_name: api
    ports:
      - 9090:8080
    links:
      - api-database
    depends_on:
      - api-database
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://api-database:27017/local